name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        run: npm run build
        env:
          REACT_APP_GITREPOREAD: ${{ secrets.REACT_APP_GITREPOREAD }}

      - name: Deploy to GitHub Pages
        run: |
          npm install -g gh
          gh auth login --with-token ${{ secrets.GH_TOKEN }}

          # Ensure the 'gh-pages' branch exists
          if git show-ref --quiet refs/heads/gh-pages; then
            git branch -D gh-pages
          fi
          
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

          git checkout --orphan gh-pages
          git reset --hard
          mv build/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages --force